# generated by datamodel-codegen:
#   filename:  frontend/identity.lookup_requested.v1.schema.json

from pydantic import BaseModel, EmailStr, Field, constr


class FrontendIdentityLookupRequestedV1DataPayload(BaseModel):
    request_id: constr(pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$') = (
        Field(
            ...,
            alias='requestId',
            description="Correlates the reply identity.resolved back to this request. Echoed verbatim in the reply's data.requestId. Lowercase canonical UUID.",
        )
    )
    email: EmailStr = Field(
        ...,
        description="The natural key Identity de-duplicates on. Known email -> existing masterId; unknown -> mint a new one. The only PII Identity ever stores. A pragmatic shape pattern is enforced (local@domain.tld, no embedded whitespace) because JSON-Schema 'format' is annotation-only; it is case-tolerant since Identity normalizes (trim + lowercase) on consume — Q&A Round 31.",
    )
