# generated by datamodel-codegen:
#   filename:  frontend/payment.captured.v1.schema.json
#   timestamp: 2026-08-02T11:02:30+00:00

from enum import StrEnum

from pydantic import BaseModel, Field, PositiveInt, constr


class Provider(StrEnum):
    mollie = 'mollie'


class Purpose(StrEnum):
    wallet_topup = 'wallet_topup'
    giftcard_purchase = 'giftcard_purchase'


class FrontendPaymentCapturedV1DataPayload(BaseModel):
    payment_id: str = Field(
        ...,
        alias='paymentId',
        description='PSP/edge payment id. Inbox dedupe key for duplicate webhook deliveries.',
    )
    provider: Provider = Field(
        ...,
        description='PSP behind the edge (v1: Mollie). Provider is swappable behind a port.',
    )
    purpose: Purpose = Field(
        ...,
        description='What the loaded value funds: a wallet top-up or a gift-card purchase.',
    )
    master_id: str | None = Field(
        None,
        alias='masterId',
        description='Canonical masterId of the paying customer. REQUIRED in practice for wallet_topup (the wallet owner); may be present or null for giftcard_purchase (a logged-in buyer, or an anonymous purchase).',
    )
    amount: PositiveInt = Field(
        ...,
        description='Captured amount in currency MINOR units (integer cents) (the value loaded). Non-taxable at load (MPV; VAT accounted at spend).',
    )
    currency: constr(pattern=r'^[A-Z]{3}$') = Field(
        ..., description="ISO 4217 code, e.g. 'EUR'."
    )
    captured_at: str = Field(
        ...,
        alias='capturedAt',
        description='When the PSP confirmed capture (RFC3339 UTC).',
    )
