# generated by datamodel-codegen:
#   filename:  frontend/privacy.erasure_requested.v1.schema.json

from enum import StrEnum

from pydantic import BaseModel, Field


class RequestedBy(StrEnum):
    self = 'self'
    admin = 'admin'


class FrontendPrivacyErasureRequestedV1DataPayload(BaseModel):
    request_id: str = Field(
        ...,
        alias='requestId',
        description='Correlates the erasure across all services and their privacy.erased acks.',
    )
    master_id: str = Field(
        ..., alias='masterId', description='Canonical masterId to erase.'
    )
    requested_by: RequestedBy = Field(
        ...,
        alias='requestedBy',
        description='Whether the data subject or an admin initiated the erasure.',
    )
    admin_actor: str | None = Field(
        None,
        alias='adminActor',
        description='The admin account when requestedBy = admin; null when self-initiated (audit attribution).',
    )
    at: str = Field(..., description='When erasure was requested (RFC3339 UTC).')
