# generated by datamodel-codegen:
#   filename:  frontend/privacy.export_requested.v1.schema.json
#   timestamp: 2026-08-02T11:02:30+00:00

from enum import StrEnum

from pydantic import BaseModel, Field


class RequestedBy(StrEnum):
    self = 'self'
    admin = 'admin'


class FrontendPrivacyExportRequestedV1DataPayload(BaseModel):
    request_id: str = Field(
        ...,
        alias='requestId',
        description='Correlates the export across services and the assembled bundle.',
    )
    master_id: str = Field(
        ..., alias='masterId', description='Canonical masterId whose data is exported.'
    )
    requested_by: RequestedBy = Field(
        ...,
        alias='requestedBy',
        description='Whether the data subject or an admin initiated the export.',
    )
    admin_actor: str | None = Field(
        None,
        alias='adminActor',
        description='The admin account when requestedBy = admin; null when self-initiated.',
    )
    at: str = Field(..., description='When the export was requested (RFC3339 UTC).')
