# generated by datamodel-codegen:
#   filename:  frontend/profile.edit_requested.v1.schema.json
#   timestamp: 2026-08-02T11:02:30+00:00

from pydantic import BaseModel, EmailStr, Field


class Racing(BaseModel):
    nickname: str | None = Field(None, description='Leaderboard nickname.')
    racing_number: str | None = Field(
        None, alias='racingNumber', description='Preferred racing number.'
    )
    kart_class: str | None = Field(
        None, alias='kartClass', description='Preferred kart class.'
    )


class Contact(BaseModel):
    legal_name: str | None = Field(None, alias='legalName')
    email: EmailStr | None = None
    phone: str | None = None
    address: str | None = None


class Consent(BaseModel):
    marketing_consent: bool | None = Field(None, alias='marketingConsent')


class FrontendProfileEditRequestedV1DataPayload(BaseModel):
    request_id: str = Field(
        ...,
        alias='requestId',
        description='Correlates the edit intent with the resulting driver/crm events.',
    )
    master_id: str = Field(
        ...,
        alias='masterId',
        description='Canonical masterId of the driver editing their profile.',
    )
    racing: Racing | None = Field(
        None, description='Driver-owned racing fields (applied by Driver).'
    )
    contact: Contact | None = Field(
        None, description='CRM-owned contact fields (applied by CRM).'
    )
    consent: Consent | None = Field(
        None, description='CRM-owned consent flags (applied by CRM).'
    )
    at: str = Field(..., description='When the edit was submitted (RFC3339 UTC).')
