# generated by datamodel-codegen:
#   filename:  frontend/schedule.change_requested.v1.schema.json
#   timestamp: 2026-08-02T11:02:30+00:00

from enum import StrEnum

from pydantic import BaseModel, Field, conint


class Action(StrEnum):
    create = 'create'
    reschedule = 'reschedule'
    capacity = 'capacity'
    cancel = 'cancel'


class FrontendScheduleChangeRequestedV1DataPayload(BaseModel):
    request_id: str = Field(
        ...,
        alias='requestId',
        description="Correlates the admin action with Booking's resulting event.",
    )
    action: Action = Field(
        ..., description='What the admin wants to do to the schedule.'
    )
    session_id: str | None = Field(
        None,
        alias='sessionId',
        description='Target session. Null when action = create (Booking assigns the id).',
    )
    planned_start: str | None = Field(
        None,
        alias='plannedStart',
        description='New planned start (for create/reschedule). RFC3339 UTC.',
    )
    planned_end: str | None = Field(
        None,
        alias='plannedEnd',
        description='New planned end (for create/reschedule). RFC3339 UTC.',
    )
    capacity: conint(ge=0) | None = Field(
        None, description='New capacity (for create/capacity).'
    )
    admin_actor: str = Field(
        ...,
        alias='adminActor',
        description='The admin account that initiated the change (for audit attribution).',
    )
    at: str = Field(..., description='When the admin issued the change (RFC3339 UTC).')
