# generated by datamodel-codegen:
#   filename:  frontend/session.control_requested.v1.schema.json
#   timestamp: 2026-08-02T11:02:30+00:00

from enum import StrEnum

from pydantic import BaseModel, Field


class Action(StrEnum):
    start = 'start'
    end = 'end'


class FrontendSessionControlRequestedV1DataPayload(BaseModel):
    request_id: str = Field(
        ...,
        alias='requestId',
        description="Correlates the control action with Timing's resulting event.",
    )
    session_id: str = Field(
        ..., alias='sessionId', description='The session to start or end.'
    )
    action: Action = Field(
        ...,
        description='Race-control action. Starting an already-started or ending a never-started session is handled gracefully (Round 14).',
    )
    admin_actor: str = Field(
        ...,
        alias='adminActor',
        description='The operator/admin account that issued the action (for audit attribution).',
    )
    at: str = Field(
        ..., description='When the operator issued the action (RFC3339 UTC).'
    )
