# generated by datamodel-codegen:
#   filename:  bar/bar.order_placed.v1.schema.json
#   timestamp: 2026-08-02T11:02:30+00:00

from pydantic import BaseModel, Field, conint


class Item(BaseModel):
    name: str = Field(..., description='Product name.')
    quantity: conint(ge=1)
    unit_price: conint(ge=0) = Field(
        ...,
        alias='unitPrice',
        description='Price per unit (currency MINOR units (integer cents)).',
    )


class BarBarOrderPlacedV1DataPayload(BaseModel):
    order_id: str = Field(
        ...,
        alias='orderId',
        description='Client-side id for inbox dedupe of double-taps.',
    )
    master_id: str | None = Field(
        None,
        alias='masterId',
        description="Canonical masterId if the order is against a driver's tab. ABSENT/null = an anonymous immediately-settled sale (no tab, no PII).",
    )
    items: list[Item] = Field(..., description='Line items in the order.', min_length=1)
    total: conint(ge=0) = Field(
        ..., description='Order total (currency MINOR units (integer cents)).'
    )
    at: str = Field(..., description='When the order was placed (RFC3339 UTC).')
