# generated by datamodel-codegen:
#   filename:  envelope.schema.json
#   timestamp: 2026-08-02T11:02:30+00:00

from typing import Any

from pydantic import BaseModel, Field, conint, constr


class PitwallMessageEnvelope(BaseModel):
    id: constr(pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$') = (
        Field(
            ...,
            description='Unique per message; the idempotent inbox dedupe key. Lowercase canonical UUID; UUID v7 RECOMMENDED (time-ordered for cheap inbox indexes + replay ordering).',
        )
    )
    type: constr(pattern=r'^[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$') = Field(
        ...,
        description="<entity>.<action>, matches the routing key, e.g. 'lap.recorded'. Facts are past-tense; intents end '.requested'.",
    )
    source: str = Field(..., description="Owning service name, e.g. 'timing'.")
    schema_version: conint(ge=1) = Field(
        ...,
        alias='schemaVersion',
        description='Payload schema version. Bumped only on a BREAKING change to the data payload; additive changes do not bump it (tolerant reader).',
    )
    envelope_version: conint(ge=1) = Field(
        ...,
        alias='envelopeVersion',
        description="Version of the envelope itself (distinct from the payload's schemaVersion), so the envelope shape can evolve independently. v1 today.",
    )
    occurred_at: constr(pattern=r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$') = (
        Field(
            ...,
            alias='occurredAt',
            description="When the fact happened. RFC3339 UTC, exactly 3-digit milliseconds, literal 'Z' (never '+00:00').",
        )
    )
    correlation_id: constr(pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$') = (
        Field(
            ...,
            alias='correlationId',
            description='Created once at the start of a flow and copied verbatim onto every downstream event (and every log line). Lowercase canonical UUID.',
        )
    )
    causation_id: (
        constr(
            pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        )
        | None
    ) = Field(..., alias='causationId', description='Id of the message that directly caused this one. Null for flow-originating events. Lowercase canonical UUID when present.')
    data: dict[str, Any] = Field(
        ...,
        description='Event-specific payload; validated against the schema for `type` + `schemaVersion`.',
    )
