// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package bar

import "time"

// A bar/POS order to charge. Published to the 'bar.events' exchange with routing
// key 'bar.order_placed'; consumed by Billing. 'masterId' is OPTIONAL: when absent
// the sale is ANONYMOUS (no tab, immediately settled, no PII) per Round 15.
// Optional masterId is additive/tolerant-reader-safe, so this stays schemaVersion
// 1.
type BarOrderPlacedV1SchemaJson struct {
	// When the order was placed (RFC3339 UTC).
	At time.Time `json:"at"`

	// Line items in the order.
	Items []BarOrderPlacedV1SchemaJsonItemsElem `json:"items"`

	// Canonical masterId if the order is against a driver's tab. ABSENT/null = an
	// anonymous immediately-settled sale (no tab, no PII).
	MasterID BarOrderPlacedV1SchemaJsonMasterID `json:"masterId"`

	// Client-side id for inbox dedupe of double-taps.
	OrderID string `json:"orderId"`

	// Order total (currency MINOR units (integer cents)).
	Total int `json:"total"`
}

type BarOrderPlacedV1SchemaJsonItemsElem struct {
	// Product name.
	Name string `json:"name"`

	// Quantity corresponds to the JSON schema field "quantity".
	Quantity int `json:"quantity"`

	// Price per unit (currency MINOR units (integer cents)).
	UnitPrice int `json:"unitPrice"`
}

// Canonical masterId if the order is against a driver's tab. ABSENT/null = an
// anonymous immediately-settled sale (no tab, no PII).
type BarOrderPlacedV1SchemaJsonMasterID *string
