# generated by datamodel-codegen:
#   filename:  driver/driver.pr_updated.v1.schema.json

from pydantic import BaseModel, Field, conint, constr


class DriverDriverPrUpdatedV1DataPayload(BaseModel):
    master_id: constr(pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') = (
        Field(
            ...,
            alias='masterId',
            description='Canonical masterId issued by Identity. Lowercase canonical UUID v4 (version nibble 4, variant nibble [89ab]); the pattern is enforced (format is annotation-only).',
        )
    )
    lap_time_ms: conint(ge=1) = Field(
        ...,
        alias='lapTimeMs',
        description='The confirmed canonical all-time best lap time for this driver, in milliseconds.',
    )
    set_at: constr(pattern=r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$') = (
        Field(
            ...,
            alias='setAt',
            description="When the record-setting lap happened (the 'at' of that lap). RFC3339 UTC, exactly 3-digit milliseconds, literal 'Z' (AR9). The pattern is enforced (format is annotation-only).",
        )
    )
