# generated by datamodel-codegen:
#   filename:  driver/driver.history_appended.v1.schema.json

from pydantic import BaseModel, Field, conint, constr


class DriverDriverHistoryAppendedV1DataPayload(BaseModel):
    master_id: constr(pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') = (
        Field(
            ...,
            alias='masterId',
            description='Canonical masterId issued by Identity. Lowercase canonical UUID v4 (version nibble 4, variant nibble [89ab]); the pattern is enforced (format is annotation-only).',
        )
    )
    session_id: str = Field(
        ...,
        alias='sessionId',
        description='The session this result belongs to. Same id space as lap.recorded.sessionId / session.ended.sessionId.',
    )
    best_lap_ms: conint(ge=1) | None = Field(
        None,
        alias='bestLapMs',
        description="The driver's best (fastest) valid lap this session, in milliseconds. Null if the driver logged no counted lap (mirrors the stored summary row); always present as a key (no omitempty, AR9).",
    )
    lap_count: conint(ge=0) | None = Field(
        None,
        alias='lapCount',
        description='Number of counted laps the driver logged this session (out-lap excluded). Null if unknown; always present as a key.',
    )
