# generated by datamodel-codegen:
#   filename:  driver/driver.profile_updated.v1.schema.json

from pydantic import BaseModel, Field, constr


class DriverDriverProfileUpdatedV1DataPayload(BaseModel):
    master_id: constr(pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') = (
        Field(
            ...,
            alias='masterId',
            description='Canonical masterId issued by Identity. Lowercase canonical UUID v4 (version nibble 4, variant nibble [89ab]); the pattern is enforced (format is annotation-only).',
        )
    )
    racing_number: str | None = Field(
        None,
        alias='racingNumber',
        description='Preferred racing number. Null until set; always present (no omitempty on a meaningful wire field, AR9).',
    )
    kart_class: str | None = Field(
        None, alias='kartClass', description='Preferred kart class. Null until set.'
    )
    nickname: str | None = Field(
        None,
        description='Leaderboard nickname. Null until set — Leaderboard falls back to racing number / a short masterId until this arrives (FR46).',
    )
