// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package privacy

import "time"

// A per-service slice of a data-export bundle. Published by each owning service to
// its OWN '<service>.events' exchange with routing key 'privacy.data_provided';
// consumed by the Control Room which assembles the full export. (ADR-0009.)
type PrivacyDataProvidedV1SchemaJson struct {
	// When the slice was produced (RFC3339 UTC).
	At time.Time `json:"at"`

	// The data subject.
	MasterID string `json:"masterId"`

	// This service's portion of the subject's personal data. Service-specific;
	// consumers (Control Room) treat it as opaque content.
	Payload PrivacyDataProvidedV1SchemaJsonPayload `json:"payload"`

	// The originating privacy.export_requested id.
	RequestID string `json:"requestId"`

	// The emitting service name (matches the envelope 'source').
	Service string `json:"service"`
}

// This service's portion of the subject's personal data. Service-specific;
// consumers (Control Room) treat it as opaque content.
type PrivacyDataProvidedV1SchemaJsonPayload map[string]interface{}

// A per-service acknowledgement that a service has erased or anonymized its local
// slice for a masterId. Published by EVERY service to its OWN '<service>.events'
// exchange with routing key 'privacy.erased'; consumed by the Control Room to
// track erasure completion. (ADR-0009.)
type PrivacyErasedV1SchemaJson struct {
	// When this service completed erasure. RFC3339 UTC, exactly 3-digit milliseconds,
	// literal 'Z' (AR9). The pattern is enforced (format is annotation-only).
	At string `json:"at"`

	// The erased masterId (now a tombstone in the emitting service).
	MasterID string `json:"masterId"`

	// deleted = local slice removed; anonymized = retained record stripped of PII
	// (Billing, under legal retention).
	Mode PrivacyErasedV1SchemaJsonMode `json:"mode"`

	// The originating privacy.erasure_requested id.
	RequestID string `json:"requestId"`

	// The emitting service name (matches the envelope 'source').
	Service string `json:"service"`
}

type PrivacyErasedV1SchemaJsonMode string

const PrivacyErasedV1SchemaJsonModeAnonymized PrivacyErasedV1SchemaJsonMode = "anonymized"
const PrivacyErasedV1SchemaJsonModeDeleted PrivacyErasedV1SchemaJsonMode = "deleted"
