// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package envelope

// Every message on the bus uses this envelope. The event-specific payload lives
// under `data` and is validated against its own schema based on `type` +
// `schemaVersion`. All JSON field names are camelCase; all UUIDs are lowercase
// canonical (readers normalize-then-validate); all timestamps are RFC3339 UTC with
// exactly 3-digit milliseconds and a literal `Z`. See contract/README.md (Wire
// Contract Rules).
type EnvelopeSchemaJson struct {
	// Id of the message that directly caused this one. Null for flow-originating
	// events. Lowercase canonical UUID when present.
	CausationID EnvelopeSchemaJsonCausationID `json:"causationId"`

	// Created once at the start of a flow and copied verbatim onto every downstream
	// event (and every log line). Lowercase canonical UUID.
	CorrelationID string `json:"correlationId"`

	// Event-specific payload; validated against the schema for `type` +
	// `schemaVersion`.
	Data EnvelopeSchemaJsonData `json:"data"`

	// Version of the envelope itself (distinct from the payload's schemaVersion), so
	// the envelope shape can evolve independently. v1 today.
	EnvelopeVersion int `json:"envelopeVersion"`

	// Unique per message; the idempotent inbox dedupe key. Lowercase canonical UUID;
	// UUID v7 RECOMMENDED (time-ordered for cheap inbox indexes + replay ordering).
	ID string `json:"id"`

	// When the fact happened. RFC3339 UTC, exactly 3-digit milliseconds, literal 'Z'
	// (never '+00:00').
	OccurredAt string `json:"occurredAt"`

	// Payload schema version. Bumped only on a BREAKING change to the data payload;
	// additive changes do not bump it (tolerant reader).
	SchemaVersion int `json:"schemaVersion"`

	// Owning service name, e.g. 'timing'.
	Source string `json:"source"`

	// <entity>.<action>, matches the routing key, e.g. 'lap.recorded'. Facts are
	// past-tense; intents end '.requested'.
	Type string `json:"type"`
}

// Id of the message that directly caused this one. Null for flow-originating
// events. Lowercase canonical UUID when present.
type EnvelopeSchemaJsonCausationID *string

// Event-specific payload; validated against the schema for `type` +
// `schemaVersion`.
type EnvelopeSchemaJsonData map[string]interface{}
