# generated by datamodel-codegen:
#   filename:  privacy/privacy.erased.v1.schema.json
#   timestamp: 2026-08-02T11:02:30+00:00

from enum import StrEnum

from pydantic import BaseModel, Field, constr


class Mode(StrEnum):
    deleted = 'deleted'
    anonymized = 'anonymized'


class PrivacyErasedV1DataPayload(BaseModel):
    request_id: str = Field(
        ...,
        alias='requestId',
        description='The originating privacy.erasure_requested id.',
    )
    master_id: str = Field(
        ...,
        alias='masterId',
        description='The erased masterId (now a tombstone in the emitting service).',
    )
    service: str = Field(
        ..., description="The emitting service name (matches the envelope 'source')."
    )
    mode: Mode = Field(
        ...,
        description='deleted = local slice removed; anonymized = retained record stripped of PII (Billing, under legal retention).',
    )
    at: constr(pattern=r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$') = (
        Field(
            ...,
            description="When this service completed erasure. RFC3339 UTC, exactly 3-digit milliseconds, literal 'Z' (AR9). The pattern is enforced (format is annotation-only).",
        )
    )
