# generated by datamodel-codegen:
#   filename:  privacy/privacy.data_provided.v1.schema.json

from typing import Any

from pydantic import BaseModel, Field


class PrivacyDataProvidedV1DataPayload(BaseModel):
    request_id: str = Field(
        ...,
        alias='requestId',
        description='The originating privacy.export_requested id.',
    )
    master_id: str = Field(..., alias='masterId', description='The data subject.')
    service: str = Field(
        ..., description="The emitting service name (matches the envelope 'source')."
    )
    payload: dict[str, Any] = Field(
        ...,
        description="This service's portion of the subject's personal data. Service-specific; consumers (Control Room) treat it as opaque content.",
    )
    at: str = Field(..., description='When the slice was produced (RFC3339 UTC).')
