// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package control

import "time"

// A 1 s liveness signal emitted by EVERY service. Like privacy.erased, it is a
// cross-cutting event: each service publishes it to its OWN '<service>.events'
// exchange (the `source` envelope field names the emitter) with routing key
// 'control.heartbeat'; the Control Room binds a wildcard and aggregates to detect
// DOWN (3 misses). The 'control' namespace reflects the catalog grouping, not the
// owning exchange. (Q&A Round 25; ADR-0004 bus-only health.)
type ControlHeartbeatV1SchemaJson struct {
	// When the heartbeat was emitted. RFC3339 UTC, exactly 3-digit milliseconds,
	// literal 'Z' (AR9). The pattern is enforced (format is annotation-only).
	At string `json:"at"`

	// Identifies the specific process/instance of the service (so the Control Room
	// can distinguish replicas). Minted once at startup.
	InstanceID string `json:"instanceId"`

	// Name of the emitting service, e.g. 'timing'. Equals the envelope `source`.
	Service string `json:"service"`
}

// The assembled data-export bundle is ready. Published by the Control Room
// (privacy aggregator) to the 'control.events' exchange with routing key
// 'privacy.export_ready'; consumed by Mailing to deliver the export to the data
// subject. (ADR-0009.)
type PrivacyExportReadyV1SchemaJson struct {
	// When the bundle was assembled (RFC3339 UTC).
	At time.Time `json:"at"`

	// Reference to the assembled export bundle (e.g. a stored file/archive id).
	DocumentRef string `json:"documentRef"`

	// The data subject the export belongs to.
	MasterID string `json:"masterId"`

	// The originating privacy.export_requested id.
	RequestID string `json:"requestId"`
}
