# generated by datamodel-codegen:
#   filename:  identity/identity.resolved.v1.schema.json

from pydantic import BaseModel, EmailStr, Field, constr


class IdentityIdentityResolvedV1DataPayload(BaseModel):
    request_id: constr(pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$') = (
        Field(
            ...,
            alias='requestId',
            description='Correlates with the originating identity.lookup_requested. Echoed verbatim from the request. Lowercase canonical UUID; the pattern is enforced (format is annotation-only).',
        )
    )
    email: EmailStr = Field(
        ...,
        description="The natural key that was looked up, in Identity's canonical (trimmed, lowercased) form — Q&A Round 31. A pragmatic shape pattern is enforced because 'format' is annotation-only.",
    )
    master_id: constr(pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') = (
        Field(
            ...,
            alias='masterId',
            description='The canonical masterId issued by Identity. Lowercase canonical UUID v4 (version nibble 4, variant nibble [89ab]); the pattern is enforced (format is annotation-only). Consumers idempotently upsert on this. Matches the lap.recorded precedent — AC1.',
        )
    )
