// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package billing

import "time"

// Billing (stored-value ledger SoT) ISSUED a bearer gift card after a confirmed
// purchase (Round 17, ADR-0011). A gift card is an anonymous, transferable
// stored-value balance redeemed by code — it carries NO PII. Published to
// 'billing.events' with routing key 'giftcard.issued'; caused by a
// 'payment.captured' (purpose=giftcard_purchase). Consumed by Bar/POS (local
// redemption table), Frontend (show in account), Mailing (deliver the code to the
// recipient).
type GiftcardIssuedV1SchemaJson struct {
	// Initial balance, currency MINOR units (integer cents). Non-taxable at issue
	// (MPV).
	Amount int `json:"amount"`

	// When the gift card was issued (RFC3339 UTC).
	At time.Time `json:"at"`

	// Bearer redemption code (the secret presented at redemption). No PII.
	Code string `json:"code"`

	// ISO 4217 code, e.g. 'EUR'.
	Currency string `json:"currency"`

	// Configurable expiry (RFC3339 UTC) with an EU-compliant minimum validity; null =
	// no expiry.
	ExpiresAt *time.Time `json:"expiresAt"`

	// Stable id for the gift card in the ledger.
	GiftCardID string `json:"giftCardId"`

	// The payment.captured paymentId that funded this gift card (trace +
	// idempotency).
	SourcePaymentID string `json:"sourcePaymentId"`
}

// Billing (stored-value ledger SoT) REDEEMED a bearer gift card — either loaded
// into a wallet or spent directly at the POS (Round 17, ADR-0011). Published to
// 'billing.events' with routing key 'giftcard.redeemed'. Redemption is idempotent
// (inbox + ledger guard): a code cannot be double-spent. Consumed by Frontend,
// Bar/POS (local balance copy), Control Room. Partial redemption supported via
// 'balanceAfter'.
type GiftcardRedeemedV1SchemaJson struct {
	// Amount redeemed in this action, currency MINOR units (integer cents).
	Amount int `json:"amount"`

	// When the redemption was applied (RFC3339 UTC).
	At time.Time `json:"at"`

	// Authoritative remaining balance on the gift card after this redemption (ECST).
	BalanceAfter int `json:"balanceAfter"`

	// ISO 4217 code, e.g. 'EUR'.
	Currency string `json:"currency"`

	// The gift card redeemed (stable ledger id).
	GiftCardID string `json:"giftCardId"`

	// Target/redeeming masterId when mode=loaded_to_wallet (the wallet) or an
	// identified driver spending at POS; null for an anonymous POS spend.
	MasterID GiftcardRedeemedV1SchemaJsonMasterID `json:"masterId"`

	// loaded_to_wallet = balance moved into a wallet; spent = redeemed directly
	// against a POS charge.
	Mode GiftcardRedeemedV1SchemaJsonMode `json:"mode"`
}

// Target/redeeming masterId when mode=loaded_to_wallet (the wallet) or an
// identified driver spending at POS; null for an anonymous POS spend.
type GiftcardRedeemedV1SchemaJsonMasterID *string

type GiftcardRedeemedV1SchemaJsonMode string

const GiftcardRedeemedV1SchemaJsonModeLoadedToWallet GiftcardRedeemedV1SchemaJsonMode = "loaded_to_wallet"
const GiftcardRedeemedV1SchemaJsonModeSpent GiftcardRedeemedV1SchemaJsonMode = "spent"

// Billing (stored-value ledger SoT) DEBITED a wallet for a spend — a balance debit
// modelled on the bus, NEVER a fresh online card charge (Round 17, ADR-0011).
// Published to 'billing.events' with routing key 'wallet.debited'. Consumed by
// Frontend (balance read-model), Bar/POS (local balance copy), Control Room.
// Partial spend supported; insufficient balance is not represented here (the
// remainder falls back to normal POS payment). VAT is accounted at this spend via
// Billing's existing document logic (MPV).
type WalletDebitedV1SchemaJson struct {
	// Amount debited, currency MINOR units (integer cents).
	Amount int `json:"amount"`

	// When the ledger applied the debit (RFC3339 UTC).
	At time.Time `json:"at"`

	// Authoritative wallet balance after this debit (ECST).
	BalanceAfter int `json:"balanceAfter"`

	// ISO 4217 code, e.g. 'EUR'.
	Currency string `json:"currency"`

	// Wallet owner (canonical masterId).
	MasterID string `json:"masterId"`

	// What the balance paid for.
	Reason WalletDebitedV1SchemaJsonReason `json:"reason"`

	// Reference to the charge it settled (e.g. orderId, tabId, bookingId), when
	// applicable.
	Ref WalletDebitedV1SchemaJsonRef `json:"ref"`
}

type WalletDebitedV1SchemaJsonReason string

const WalletDebitedV1SchemaJsonReasonBar WalletDebitedV1SchemaJsonReason = "bar"
const WalletDebitedV1SchemaJsonReasonBooking WalletDebitedV1SchemaJsonReason = "booking"
const WalletDebitedV1SchemaJsonReasonPosSale WalletDebitedV1SchemaJsonReason = "pos_sale"
const WalletDebitedV1SchemaJsonReasonSession WalletDebitedV1SchemaJsonReason = "session"

// Reference to the charge it settled (e.g. orderId, tabId, bookingId), when
// applicable.
type WalletDebitedV1SchemaJsonRef *string

// Billing (the stored-value ledger system-of-record) CREDITED a wallet after a
// confirmed load (Round 17, ADR-0011). Published to 'billing.events' with routing
// key 'wallet.topped_up'; caused by a 'payment.captured'. Consumed by Frontend
// (account balance read-model), Bar/POS (local balance copy for spend), Control
// Room. 'balanceAfter' carries the authoritative balance (ECST). Non-taxable load
// (MPV).
type WalletToppedUpV1SchemaJson struct {
	// Amount credited, currency MINOR units (integer cents).
	Amount int `json:"amount"`

	// When the ledger applied the credit (RFC3339 UTC).
	At time.Time `json:"at"`

	// Authoritative wallet balance after this credit (ECST: consumers replace, not
	// accumulate).
	BalanceAfter int `json:"balanceAfter"`

	// ISO 4217 code, e.g. 'EUR'.
	Currency string `json:"currency"`

	// Wallet owner (canonical masterId).
	MasterID string `json:"masterId"`

	// The payment.captured paymentId that funded this top-up (trace + idempotency).
	SourcePaymentID string `json:"sourcePaymentId"`
}
