# generated by datamodel-codegen:
#   filename:  timing/driver.checked_in.v1.schema.json

from enum import StrEnum

from pydantic import BaseModel, Field, constr


class CheckInMethod(StrEnum):
    qr = 'qr'
    transponder = 'transponder'


class TimingDriverCheckedInV1DataPayload(BaseModel):
    master_id: constr(pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') = (
        Field(
            ...,
            alias='masterId',
            description='Canonical masterId issued by Identity. Lowercase canonical UUID v4 (version nibble 4, variant nibble [89ab]); the pattern is enforced (format is annotation-only). Read directly from the QR, or resolved from the transponder map. Timing never mints it.',
        )
    )
    at: constr(pattern=r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$') = (
        Field(
            ...,
            description="When the gate scan happened. RFC3339 UTC, exactly 3-digit milliseconds, literal 'Z' (AR9). The pattern is enforced (format is annotation-only).",
        )
    )
    check_in_method: CheckInMethod = Field(
        ...,
        alias='checkInMethod',
        description="How the driver was identified at the gate: 'qr' (masterId read directly from the QR, no lookup) or 'transponder' (hardware id resolved via Timing's local map).",
    )
    transponder_id: str | None = Field(
        None,
        alias='transponderId',
        description="The hardware id when checkInMethod is 'transponder'; null for QR drivers. Always present (no omitempty on a meaningful wire field, AR9).",
    )
