# generated by datamodel-codegen:
#   filename:  timing/lap.recorded.v1.schema.json
#   timestamp: 2026-08-02T11:02:30+00:00

from pydantic import BaseModel, Field, conint, constr


class TimingLapRecordedV1DataPayload(BaseModel):
    master_id: constr(pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') = (
        Field(
            ...,
            alias='masterId',
            description='Canonical masterId issued by Identity. Lowercase canonical UUID v4 (version nibble 4, variant nibble [89ab]); the pattern is enforced (format is annotation-only).',
        )
    )
    session_id: str = Field(
        ..., alias='sessionId', description='Session the lap belongs to.'
    )
    lap_number: conint(ge=1) = Field(
        ...,
        alias='lapNumber',
        description='1-based; the out-lap (first crossing) is not counted.',
    )
    lap_time_ms: conint(ge=1) = Field(
        ...,
        alias='lapTimeMs',
        description='Milliseconds since the previous valid crossing.',
    )
    at: constr(pattern=r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$') = (
        Field(
            ...,
            description="When the crossing happened. RFC3339 UTC, exactly 3-digit milliseconds, literal 'Z' (AR9). The pattern is enforced (format is annotation-only).",
        )
    )
    transponder_id: str | None = Field(
        None,
        alias='transponderId',
        description='Hardware id if detected via transponder rather than QR. Optional.',
    )
