# generated by datamodel-codegen:
#   filename:  timing/personal_record.broken.v1.schema.json

from pydantic import BaseModel, Field, conint, constr


class TimingPersonalRecordBrokenV1DataPayload(BaseModel):
    master_id: constr(pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') = (
        Field(
            ...,
            alias='masterId',
            description='Canonical masterId issued by Identity. Lowercase canonical UUID v4 (version nibble 4, variant nibble [89ab]); the pattern is enforced (format is annotation-only).',
        )
    )
    session_id: str = Field(
        ...,
        alias='sessionId',
        description='Session the record-setting lap belongs to. Same id space as lap.recorded.sessionId / session.ended.sessionId.',
    )
    lap_time_ms: conint(ge=1) = Field(
        ...,
        alias='lapTimeMs',
        description='The record-setting lap time, in milliseconds (the new best).',
    )
    previous_ms: conint(ge=1) | None = Field(
        None,
        alias='previousMs',
        description='The all-time PR that was just beaten, in milliseconds. OPTIONAL: absent on a first-ever PR (nothing to beat). When present, it is strictly greater than lapTimeMs.',
    )
