# generated by datamodel-codegen:
#   filename:  timing/scanner.online.v1.schema.json

from pydantic import BaseModel, Field, constr


class TimingScannerOnlineV1DataPayload(BaseModel):
    scanner_id: str = Field(
        ...,
        alias='scannerId',
        description='The scanner that recovered. Currently the fixed start-finish line scanner ("start-finish"); kept a plain string for a future multi-scanner world. Matches the scannerId of the scanner.offline that opened the gap.',
    )
    at: constr(pattern=r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$') = (
        Field(
            ...,
            description="When the scanner recovered (crossings resume). RFC3339 UTC, exactly 3-digit milliseconds, literal 'Z' (AR9). The pattern is enforced (format is annotation-only).",
        )
    )
