# generated by datamodel-codegen:
#   filename:  timing/scanner.offline.v1.schema.json

from pydantic import BaseModel, Field, constr


class TimingScannerOfflineV1DataPayload(BaseModel):
    scanner_id: str = Field(
        ...,
        alias='scannerId',
        description='The scanner that went silent. Currently the fixed start-finish line scanner ("start-finish") — the only scanner that produces laps and the only one this story concerns; kept a plain string for a future multi-scanner world.',
    )
    since: constr(pattern=r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$') = (
        Field(
            ...,
            description="When the scanner was detected offline (the outage start / detection instant). RFC3339 UTC, exactly 3-digit milliseconds, literal 'Z' (AR9). The pattern is enforced (format is annotation-only).",
        )
    )
    gap_from: constr(pattern=r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$') = (
        Field(
            ...,
            alias='gapFrom',
            description="The wire time of the last good crossing before the gap — so a consumer knows from when crossings may be missing. Equals 'since' when no crossing has happened yet this session. Same timestamp shape as 'since'.",
        )
    )
