# generated by datamodel-codegen:
#   filename:  timing/session.started.v1.schema.json

from pydantic import BaseModel, Field, constr


class TimingSessionStartedV1DataPayload(BaseModel):
    session_id: str = Field(
        ...,
        alias='sessionId',
        description='The session that started. Same id space as lap.recorded.sessionId.',
    )
    started_at: constr(pattern=r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$') = (
        Field(
            ...,
            alias='startedAt',
            description="When the session actually started. RFC3339 UTC, exactly 3-digit milliseconds, literal 'Z' (AR9). The pattern is enforced (format is annotation-only).",
        )
    )
