# generated by datamodel-codegen:
#   filename:  timing/session.ended.v1.schema.json

from typing import Any

from pydantic import BaseModel, Field, constr


class TimingSessionEndedV1DataPayload(BaseModel):
    session_id: str = Field(
        ...,
        alias='sessionId',
        description='The session that ended. Same id space as lap.recorded.sessionId.',
    )
    ended_at: constr(pattern=r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$') = (
        Field(
            ...,
            alias='endedAt',
            description="When the session actually ended. RFC3339 UTC, exactly 3-digit milliseconds, literal 'Z' (AR9). The pattern is enforced (format is annotation-only).",
        )
    )
    summary: list[dict[str, Any]] = Field(
        ...,
        description='Per-session result rows (e.g. one per driver, with lap times). Item shape intentionally unpinned for v1 — tolerant object.',
    )
