# generated by datamodel-codegen:
#   filename:  timing/session.ended.v1.schema.json

from pydantic import BaseModel, Field, conint, constr


class SummaryItem(BaseModel):
    master_id: constr(pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') = (
        Field(
            ...,
            alias='masterId',
            description='Canonical masterId issued by Identity. Lowercase canonical UUID v4 (version nibble 4, variant nibble [89ab]); the pattern is enforced (format is annotation-only).',
        )
    )
    best_lap_ms: conint(ge=1) | None = Field(
        None,
        alias='bestLapMs',
        description="The driver's best (fastest) valid lap this session, in milliseconds. Optional — absent if the driver logged no counted lap.",
    )
    lap_count: conint(ge=0) | None = Field(
        None,
        alias='lapCount',
        description='Number of counted laps the driver logged this session (out-lap excluded). Optional.',
    )


class TimingSessionEndedV1DataPayload(BaseModel):
    session_id: str = Field(
        ...,
        alias='sessionId',
        description='The session that ended. Same id space as lap.recorded.sessionId.',
    )
    ended_at: constr(pattern=r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$') = (
        Field(
            ...,
            alias='endedAt',
            description="When the session actually ended. RFC3339 UTC, exactly 3-digit milliseconds, literal 'Z' (AR9). The pattern is enforced (format is annotation-only).",
        )
    )
    summary: list[SummaryItem] = Field(
        ...,
        description='Per-session result rows, one per driver. Item shape pinned in v1 (Story 3.3, Q36.1): masterId required, bestLapMs/lapCount optional; the item stays a tolerant object (additive fields allowed).',
    )
