// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package driver

// Driver stored one driver's per-session result. Published to the 'driver.events'
// exchange with routing key 'driver.history_appended'. Emitted ONE-PER-DRIVER when
// Driver consumes a timing/session.ended (Story 3.3, Q&A Round 36 / Q36.2): each
// row of session.ended.summary[] becomes its own driver.history_appended so a
// consumer (Frontend) can key its per-driver read-model update off masterId
// without unpacking an array. bestLapMs/lapCount mirror the stored summary row
// (contract/schemas/timing/session.ended.v1.schema.json's summary items); this is
// a session-scoped result, NOT the canonical all-time PR (that is
// driver.pr_updated, Story 3.4).
type DriverHistoryAppendedV1SchemaJson struct {
	// The driver's best (fastest) valid lap this session, in milliseconds. Null if
	// the driver logged no counted lap (mirrors the stored summary row); always
	// present as a key (no omitempty, AR9).
	BestLapMs DriverHistoryAppendedV1SchemaJsonBestLapMs `json:"bestLapMs"`

	// Number of counted laps the driver logged this session (out-lap excluded). Null
	// if unknown; always present as a key.
	LapCount DriverHistoryAppendedV1SchemaJsonLapCount `json:"lapCount"`

	// Canonical masterId issued by Identity. Lowercase canonical UUID v4 (version
	// nibble 4, variant nibble [89ab]); the pattern is enforced (format is
	// annotation-only).
	MasterID string `json:"masterId"`

	// The session this result belongs to. Same id space as lap.recorded.sessionId /
	// session.ended.sessionId.
	SessionID string `json:"sessionId"`
}

// The driver's best (fastest) valid lap this session, in milliseconds. Null if the
// driver logged no counted lap (mirrors the stored summary row); always present as
// a key (no omitempty, AR9).
type DriverHistoryAppendedV1SchemaJsonBestLapMs *int

// Number of counted laps the driver logged this session (out-lap excluded). Null
// if unknown; always present as a key.
type DriverHistoryAppendedV1SchemaJsonLapCount *int

// Driver (system of record for the racing identity) confirmed a new canonical
// all-time personal record for a driver, computed authoritatively from its own lap
// history (Story 3.4, FR11 / Q&A Round 37 / Q37.4). Published to the
// 'driver.events' exchange with routing key 'driver.pr_updated' — one event per
// real change to the canonical PR (idempotent: an already-confirmed PR
// re-publishes nothing). Timing consumes it to refresh its local PR copy (FR37);
// Frontend updates its read-model.
type DriverPrUpdatedV1SchemaJson struct {
	// The confirmed canonical all-time best lap time for this driver, in
	// milliseconds.
	LapTimeMs int `json:"lapTimeMs"`

	// Canonical masterId issued by Identity. Lowercase canonical UUID v4 (version
	// nibble 4, variant nibble [89ab]); the pattern is enforced (format is
	// annotation-only).
	MasterID string `json:"masterId"`

	// When the record-setting lap happened (the 'at' of that lap). RFC3339 UTC,
	// exactly 3-digit milliseconds, literal 'Z' (AR9). The pattern is enforced
	// (format is annotation-only).
	SetAt string `json:"setAt"`
}

// Driver's racing profile (identity/preference fields) for a masterId changed, or
// was created for the first time via the minimal-profile safety net. Published to
// the 'driver.events' exchange with routing key 'driver.profile_updated'. Field
// names/types mirror the 'racing' branch of
// contract/schemas/frontend/profile.edit_requested.v1.schema.json exactly (Q&A
// Round 35/Q35.1). Carries no PR/history stats — those are driver.pr_updated and
// driver.history_appended's own concern (Stories 3.4/3.3), never duplicated here.
type DriverProfileUpdatedV1SchemaJson struct {
	// Preferred kart class. Null until set.
	KartClass DriverProfileUpdatedV1SchemaJsonKartClass `json:"kartClass"`

	// Canonical masterId issued by Identity. Lowercase canonical UUID v4 (version
	// nibble 4, variant nibble [89ab]); the pattern is enforced (format is
	// annotation-only).
	MasterID string `json:"masterId"`

	// Leaderboard nickname. Null until set — Leaderboard falls back to racing number
	// / a short masterId until this arrives (FR46).
	Nickname DriverProfileUpdatedV1SchemaJsonNickname `json:"nickname"`

	// Preferred racing number. Null until set; always present (no omitempty on a
	// meaningful wire field, AR9).
	RacingNumber DriverProfileUpdatedV1SchemaJsonRacingNumber `json:"racingNumber"`
}

// Preferred kart class. Null until set.
type DriverProfileUpdatedV1SchemaJsonKartClass *string

// Leaderboard nickname. Null until set — Leaderboard falls back to racing number /
// a short masterId until this arrives (FR46).
type DriverProfileUpdatedV1SchemaJsonNickname *string

// Preferred racing number. Null until set; always present (no omitempty on a
// meaningful wire field, AR9).
type DriverProfileUpdatedV1SchemaJsonRacingNumber *string
