// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package driver

// Driver's racing profile (identity/preference fields) for a masterId changed, or
// was created for the first time via the minimal-profile safety net. Published to
// the 'driver.events' exchange with routing key 'driver.profile_updated'. Field
// names/types mirror the 'racing' branch of
// contract/schemas/frontend/profile.edit_requested.v1.schema.json exactly (Q&A
// Round 35/Q35.1). Carries no PR/history stats — those are driver.pr_updated and
// driver.history_appended's own concern (Stories 3.4/3.3), never duplicated here.
type DriverProfileUpdatedV1SchemaJson struct {
	// Preferred kart class. Null until set.
	KartClass DriverProfileUpdatedV1SchemaJsonKartClass `json:"kartClass"`

	// Canonical masterId issued by Identity. Lowercase canonical UUID v4 (version
	// nibble 4, variant nibble [89ab]); the pattern is enforced (format is
	// annotation-only).
	MasterID string `json:"masterId"`

	// Leaderboard nickname. Null until set — Leaderboard falls back to racing number
	// / a short masterId until this arrives (FR46).
	Nickname DriverProfileUpdatedV1SchemaJsonNickname `json:"nickname"`

	// Preferred racing number. Null until set; always present (no omitempty on a
	// meaningful wire field, AR9).
	RacingNumber DriverProfileUpdatedV1SchemaJsonRacingNumber `json:"racingNumber"`
}

// Preferred kart class. Null until set.
type DriverProfileUpdatedV1SchemaJsonKartClass *string

// Leaderboard nickname. Null until set — Leaderboard falls back to racing number /
// a short masterId until this arrives (FR46).
type DriverProfileUpdatedV1SchemaJsonNickname *string

// Preferred racing number. Null until set; always present (no omitempty on a
// meaningful wire field, AR9).
type DriverProfileUpdatedV1SchemaJsonRacingNumber *string
