# generated by datamodel-codegen:
#   filename:  control/control.heartbeat.v1.schema.json

from pydantic import BaseModel, Field, constr


class ControlControlHeartbeatV1DataPayload(BaseModel):
    service: str = Field(
        ...,
        description="Name of the emitting service, e.g. 'timing'. Equals the envelope `source`.",
    )
    at: constr(pattern=r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$') = (
        Field(
            ...,
            description="When the heartbeat was emitted. RFC3339 UTC, exactly 3-digit milliseconds, literal 'Z' (AR9). The pattern is enforced (format is annotation-only).",
        )
    )
    instance_id: str = Field(
        ...,
        alias='instanceId',
        description='Identifies the specific process/instance of the service (so the Control Room can distinguish replicas). Minted once at startup.',
    )
