# generated by datamodel-codegen:
#   filename:  control/privacy.export_ready.v1.schema.json

from pydantic import BaseModel, Field


class ControlPrivacyExportReadyV1DataPayload(BaseModel):
    request_id: str = Field(
        ...,
        alias='requestId',
        description='The originating privacy.export_requested id.',
    )
    master_id: str = Field(
        ..., alias='masterId', description='The data subject the export belongs to.'
    )
    document_ref: str = Field(
        ...,
        alias='documentRef',
        description='Reference to the assembled export bundle (e.g. a stored file/archive id).',
    )
    at: str = Field(..., description='When the bundle was assembled (RFC3339 UTC).')
