// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package frontend

import "time"

// A request for the canonical masterId for an email. Originates from a
// register-first flow (Frontend online registration; the counter/kiosk in later
// epics) and is published to the ORIGINATING service's own exchange (e.g.
// frontend.events). Identity binds and replies identity.resolved. The requester
// never mints an id (FR1/FR39).
type IdentityLookupRequestedV1SchemaJson struct {
	// The natural key Identity de-duplicates on. Known email -> existing masterId;
	// unknown -> mint a new one. The only PII Identity ever stores. A pragmatic shape
	// pattern is enforced (local@domain.tld, no embedded whitespace) because
	// JSON-Schema 'format' is annotation-only; it is case-tolerant since Identity
	// normalizes (trim + lowercase) on consume — Q&A Round 31.
	Email string `json:"email"`

	// Correlates the reply identity.resolved back to this request. Echoed verbatim in
	// the reply's data.requestId. Lowercase canonical UUID.
	RequestID string `json:"requestId"`
}

// An online card payment was CONFIRMED captured by the PSP at the Frontend
// payments edge, to LOAD stored value (the only online card operation; Round 17,
// ADR-0011). Published to 'frontend.events' with routing key 'payment.captured';
// consumed by Billing (which credits the stored-value ledger and emits the balance
// fact). The edge emits this from its OUTBOX, so a confirmed payment survives the
// bus being down. 'paymentId' is the dedupe key for duplicate PSP webhooks.
type PaymentCapturedV1SchemaJson struct {
	// Captured amount in currency MINOR units (integer cents) (the value loaded).
	// Non-taxable at load (MPV; VAT accounted at spend).
	Amount int `json:"amount"`

	// When the PSP confirmed capture (RFC3339 UTC).
	CapturedAt time.Time `json:"capturedAt"`

	// ISO 4217 code, e.g. 'EUR'.
	Currency string `json:"currency"`

	// Canonical masterId of the paying customer. REQUIRED in practice for
	// wallet_topup (the wallet owner); may be present or null for giftcard_purchase
	// (a logged-in buyer, or an anonymous purchase).
	MasterID PaymentCapturedV1SchemaJsonMasterID `json:"masterId"`

	// PSP/edge payment id. Inbox dedupe key for duplicate webhook deliveries.
	PaymentID string `json:"paymentId"`

	// PSP behind the edge (v1: Mollie). Provider is swappable behind a port.
	Provider PaymentCapturedV1SchemaJsonProvider `json:"provider"`

	// What the loaded value funds: a wallet top-up or a gift-card purchase.
	Purpose PaymentCapturedV1SchemaJsonPurpose `json:"purpose"`
}

// Canonical masterId of the paying customer. REQUIRED in practice for wallet_topup
// (the wallet owner); may be present or null for giftcard_purchase (a logged-in
// buyer, or an anonymous purchase).
type PaymentCapturedV1SchemaJsonMasterID *string

type PaymentCapturedV1SchemaJsonProvider string

const PaymentCapturedV1SchemaJsonProviderMollie PaymentCapturedV1SchemaJsonProvider = "mollie"

type PaymentCapturedV1SchemaJsonPurpose string

const PaymentCapturedV1SchemaJsonPurposeGiftcardPurchase PaymentCapturedV1SchemaJsonPurpose = "giftcard_purchase"
const PaymentCapturedV1SchemaJsonPurposeWalletTopup PaymentCapturedV1SchemaJsonPurpose = "wallet_topup"

// A right-to-be-forgotten request. Published to the 'frontend.events' exchange
// with routing key 'privacy.erasure_requested'; EVERY service consumes it, deletes
// or anonymizes its local slice for the masterId, and emits privacy.erased.
// (ADR-0009.)
type PrivacyErasureRequestedV1SchemaJson struct {
	// The admin account when requestedBy = admin; null when self-initiated (audit
	// attribution).
	AdminActor PrivacyErasureRequestedV1SchemaJsonAdminActor `json:"adminActor"`

	// When erasure was requested (RFC3339 UTC).
	At time.Time `json:"at"`

	// Canonical masterId to erase.
	MasterID string `json:"masterId"`

	// Correlates the erasure across all services and their privacy.erased acks.
	RequestID string `json:"requestId"`

	// Whether the data subject or an admin initiated the erasure.
	RequestedBy PrivacyErasureRequestedV1SchemaJsonRequestedBy `json:"requestedBy"`
}

// The admin account when requestedBy = admin; null when self-initiated (audit
// attribution).
type PrivacyErasureRequestedV1SchemaJsonAdminActor *string

type PrivacyErasureRequestedV1SchemaJsonRequestedBy string

const PrivacyErasureRequestedV1SchemaJsonRequestedByAdmin PrivacyErasureRequestedV1SchemaJsonRequestedBy = "admin"
const PrivacyErasureRequestedV1SchemaJsonRequestedBySelf PrivacyErasureRequestedV1SchemaJsonRequestedBy = "self"

// A data-portability request. Published to the 'frontend.events' exchange with
// routing key 'privacy.export_requested'; each owning service replies with
// privacy.data_provided, the Control Room assembles the bundle, Mailing delivers
// it. (ADR-0009.)
type PrivacyExportRequestedV1SchemaJson struct {
	// The admin account when requestedBy = admin; null when self-initiated.
	AdminActor PrivacyExportRequestedV1SchemaJsonAdminActor `json:"adminActor"`

	// When the export was requested (RFC3339 UTC).
	At time.Time `json:"at"`

	// Canonical masterId whose data is exported.
	MasterID string `json:"masterId"`

	// Correlates the export across services and the assembled bundle.
	RequestID string `json:"requestId"`

	// Whether the data subject or an admin initiated the export.
	RequestedBy PrivacyExportRequestedV1SchemaJsonRequestedBy `json:"requestedBy"`
}

// The admin account when requestedBy = admin; null when self-initiated.
type PrivacyExportRequestedV1SchemaJsonAdminActor *string

type PrivacyExportRequestedV1SchemaJsonRequestedBy string

const PrivacyExportRequestedV1SchemaJsonRequestedByAdmin PrivacyExportRequestedV1SchemaJsonRequestedBy = "admin"
const PrivacyExportRequestedV1SchemaJsonRequestedBySelf PrivacyExportRequestedV1SchemaJsonRequestedBy = "self"

// A driver editing their own profile. Published to the 'frontend.events' exchange
// with routing key 'profile.edit_requested'; Driver applies racing fields, CRM
// applies contact + consent. Each consumer updates only the fields it owns. (Q1.5
// / Q8.3.)
type ProfileEditRequestedV1SchemaJson struct {
	// When the edit was submitted (RFC3339 UTC).
	At time.Time `json:"at"`

	// CRM-owned consent flags (applied by CRM).
	Consent *ProfileEditRequestedV1SchemaJsonConsent `json:"consent"`

	// CRM-owned contact fields (applied by CRM).
	Contact *ProfileEditRequestedV1SchemaJsonContact `json:"contact"`

	// Canonical masterId of the driver editing their profile.
	MasterID string `json:"masterId"`

	// Driver-owned racing fields (applied by Driver).
	Racing *ProfileEditRequestedV1SchemaJsonRacing `json:"racing"`

	// Correlates the edit intent with the resulting driver/crm events.
	RequestID string `json:"requestId"`
}

// CRM-owned consent flags (applied by CRM).
type ProfileEditRequestedV1SchemaJsonConsent struct {
	// MarketingConsent corresponds to the JSON schema field "marketingConsent".
	MarketingConsent *bool `json:"marketingConsent"`
}

// CRM-owned contact fields (applied by CRM).
type ProfileEditRequestedV1SchemaJsonContact struct {
	// Address corresponds to the JSON schema field "address".
	Address *string `json:"address"`

	// Email corresponds to the JSON schema field "email".
	Email *string `json:"email"`

	// LegalName corresponds to the JSON schema field "legalName".
	LegalName *string `json:"legalName"`

	// Phone corresponds to the JSON schema field "phone".
	Phone *string `json:"phone"`
}

// Driver-owned racing fields (applied by Driver).
type ProfileEditRequestedV1SchemaJsonRacing struct {
	// Preferred kart class.
	KartClass *string `json:"kartClass"`

	// Leaderboard nickname.
	Nickname *string `json:"nickname"`

	// Preferred racing number.
	RacingNumber *string `json:"racingNumber"`
}

// An operator/admin schedule change. Published to the 'frontend.events' exchange
// with routing key 'schedule.change_requested'; consumed by Booking, which remains
// the single authority on capacity and applies the change. (ADR-0010.)
type ScheduleChangeRequestedV1SchemaJson struct {
	// What the admin wants to do to the schedule.
	Action ScheduleChangeRequestedV1SchemaJsonAction `json:"action"`

	// The admin account that initiated the change (for audit attribution).
	AdminActor string `json:"adminActor"`

	// When the admin issued the change (RFC3339 UTC).
	At time.Time `json:"at"`

	// New capacity (for create/capacity).
	Capacity ScheduleChangeRequestedV1SchemaJsonCapacity `json:"capacity"`

	// New planned end (for create/reschedule). RFC3339 UTC.
	PlannedEnd *time.Time `json:"plannedEnd"`

	// New planned start (for create/reschedule). RFC3339 UTC.
	PlannedStart *time.Time `json:"plannedStart"`

	// Correlates the admin action with Booking's resulting event.
	RequestID string `json:"requestId"`

	// Target session. Null when action = create (Booking assigns the id).
	SessionID ScheduleChangeRequestedV1SchemaJsonSessionID `json:"sessionId"`
}

type ScheduleChangeRequestedV1SchemaJsonAction string

const ScheduleChangeRequestedV1SchemaJsonActionCancel ScheduleChangeRequestedV1SchemaJsonAction = "cancel"
const ScheduleChangeRequestedV1SchemaJsonActionCapacity ScheduleChangeRequestedV1SchemaJsonAction = "capacity"
const ScheduleChangeRequestedV1SchemaJsonActionCreate ScheduleChangeRequestedV1SchemaJsonAction = "create"
const ScheduleChangeRequestedV1SchemaJsonActionReschedule ScheduleChangeRequestedV1SchemaJsonAction = "reschedule"

// New capacity (for create/capacity).
type ScheduleChangeRequestedV1SchemaJsonCapacity *int

// Target session. Null when action = create (Booking assigns the id).
type ScheduleChangeRequestedV1SchemaJsonSessionID *string

// An operator race-control action to start or end a session. Published to the
// 'frontend.events' exchange with routing key 'session.control_requested';
// consumed by Timing, which turns it into the ACTUAL session.started /
// session.ended. (ADR-0010.)
type SessionControlRequestedV1SchemaJson struct {
	// Race-control action. Starting an already-started or ending a never-started
	// session is handled gracefully (Round 14).
	Action SessionControlRequestedV1SchemaJsonAction `json:"action"`

	// The operator/admin account that issued the action (for audit attribution).
	AdminActor string `json:"adminActor"`

	// When the operator issued the action (RFC3339 UTC).
	At time.Time `json:"at"`

	// Correlates the control action with Timing's resulting event.
	RequestID string `json:"requestId"`

	// The session to start or end.
	SessionID string `json:"sessionId"`
}

type SessionControlRequestedV1SchemaJsonAction string

const SessionControlRequestedV1SchemaJsonActionEnd SessionControlRequestedV1SchemaJsonAction = "end"
const SessionControlRequestedV1SchemaJsonActionStart SessionControlRequestedV1SchemaJsonAction = "start"
