// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package identity

// Identity's reply to an identity.lookup_requested. Returns the canonical masterId
// for an email (minted if new, reused if known). No isNew flag by design.
type IdentityResolvedV1SchemaJson struct {
	// The natural key that was looked up, in Identity's canonical (trimmed,
	// lowercased) form — Q&A Round 31. A pragmatic shape pattern is enforced because
	// 'format' is annotation-only.
	Email string `json:"email"`

	// The canonical masterId issued by Identity. Lowercase canonical UUID v4 (version
	// nibble 4, variant nibble [89ab]); the pattern is enforced (format is
	// annotation-only). Consumers idempotently upsert on this. Matches the
	// lap.recorded precedent — AC1.
	MasterID string `json:"masterId"`

	// Correlates with the originating identity.lookup_requested. Echoed verbatim from
	// the request. Lowercase canonical UUID; the pattern is enforced (format is
	// annotation-only).
	RequestID string `json:"requestId"`
}
