# generated by datamodel-codegen:
#   filename:  billing/giftcard.redeemed.v1.schema.json
#   timestamp: 2026-08-02T11:02:30+00:00

from enum import StrEnum

from pydantic import BaseModel, Field, PositiveInt, conint, constr


class Mode(StrEnum):
    loaded_to_wallet = 'loaded_to_wallet'
    spent = 'spent'


class BillingGiftcardRedeemedV1DataPayload(BaseModel):
    gift_card_id: str = Field(
        ...,
        alias='giftCardId',
        description='The gift card redeemed (stable ledger id).',
    )
    mode: Mode = Field(
        ...,
        description='loaded_to_wallet = balance moved into a wallet; spent = redeemed directly against a POS charge.',
    )
    amount: PositiveInt = Field(
        ...,
        description='Amount redeemed in this action, currency MINOR units (integer cents).',
    )
    currency: constr(pattern=r'^[A-Z]{3}$') = Field(
        ..., description="ISO 4217 code, e.g. 'EUR'."
    )
    balance_after: conint(ge=0) = Field(
        ...,
        alias='balanceAfter',
        description='Authoritative remaining balance on the gift card after this redemption (ECST).',
    )
    master_id: str | None = Field(
        None,
        alias='masterId',
        description='Target/redeeming masterId when mode=loaded_to_wallet (the wallet) or an identified driver spending at POS; null for an anonymous POS spend.',
    )
    at: str = Field(..., description='When the redemption was applied (RFC3339 UTC).')
