# generated by datamodel-codegen:
#   filename:  billing/giftcard.issued.v1.schema.json

from pydantic import BaseModel, Field, PositiveInt, constr


class BillingGiftcardIssuedV1DataPayload(BaseModel):
    gift_card_id: str = Field(
        ...,
        alias='giftCardId',
        description='Stable id for the gift card in the ledger.',
    )
    code: str = Field(
        ...,
        description='Bearer redemption code (the secret presented at redemption). No PII.',
    )
    amount: PositiveInt = Field(
        ...,
        description='Initial balance, currency MINOR units (integer cents). Non-taxable at issue (MPV).',
    )
    currency: constr(pattern=r'^[A-Z]{3}$') = Field(
        ..., description="ISO 4217 code, e.g. 'EUR'."
    )
    expires_at: str | None = Field(
        None,
        alias='expiresAt',
        description='Configurable expiry (RFC3339 UTC) with an EU-compliant minimum validity; null = no expiry.',
    )
    source_payment_id: str = Field(
        ...,
        alias='sourcePaymentId',
        description='The payment.captured paymentId that funded this gift card (trace + idempotency).',
    )
    at: str = Field(..., description='When the gift card was issued (RFC3339 UTC).')
