# generated by datamodel-codegen:
#   filename:  billing/wallet.topped_up.v1.schema.json

from pydantic import BaseModel, Field, PositiveInt, conint, constr


class BillingWalletToppedUpV1DataPayload(BaseModel):
    master_id: str = Field(
        ..., alias='masterId', description='Wallet owner (canonical masterId).'
    )
    amount: PositiveInt = Field(
        ..., description='Amount credited, currency MINOR units (integer cents).'
    )
    currency: constr(pattern=r'^[A-Z]{3}$') = Field(
        ..., description="ISO 4217 code, e.g. 'EUR'."
    )
    balance_after: conint(ge=0) = Field(
        ...,
        alias='balanceAfter',
        description='Authoritative wallet balance after this credit (ECST: consumers replace, not accumulate).',
    )
    source_payment_id: str = Field(
        ...,
        alias='sourcePaymentId',
        description='The payment.captured paymentId that funded this top-up (trace + idempotency).',
    )
    at: str = Field(
        ..., description='When the ledger applied the credit (RFC3339 UTC).'
    )
