# generated by datamodel-codegen:
#   filename:  billing/wallet.debited.v1.schema.json
#   timestamp: 2026-08-02T11:02:30+00:00

from enum import StrEnum

from pydantic import BaseModel, Field, PositiveInt, conint, constr


class Reason(StrEnum):
    pos_sale = 'pos_sale'
    session = 'session'
    booking = 'booking'
    bar = 'bar'


class BillingWalletDebitedV1DataPayload(BaseModel):
    master_id: str = Field(
        ..., alias='masterId', description='Wallet owner (canonical masterId).'
    )
    amount: PositiveInt = Field(
        ..., description='Amount debited, currency MINOR units (integer cents).'
    )
    currency: constr(pattern=r'^[A-Z]{3}$') = Field(
        ..., description="ISO 4217 code, e.g. 'EUR'."
    )
    balance_after: conint(ge=0) = Field(
        ...,
        alias='balanceAfter',
        description='Authoritative wallet balance after this debit (ECST).',
    )
    reason: Reason = Field(..., description='What the balance paid for.')
    ref: str | None = Field(
        None,
        description='Reference to the charge it settled (e.g. orderId, tabId, bookingId), when applicable.',
    )
    at: str = Field(..., description='When the ledger applied the debit (RFC3339 UTC).')
