// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package timing

// A driver identified at the entry gate (check-in). Published to the
// 'timing.events' exchange with routing key 'driver.checked_in'. QR codes embed
// the masterId (read directly, no lookup); transponders carry a hardware id
// resolved via Timing's local transponder->masterId map.
type DriverCheckedInV1SchemaJson struct {
	// When the gate scan happened. RFC3339 UTC, exactly 3-digit milliseconds, literal
	// 'Z' (AR9). The pattern is enforced (format is annotation-only).
	At string `json:"at"`

	// How the driver was identified at the gate: 'qr' (masterId read directly from
	// the QR, no lookup) or 'transponder' (hardware id resolved via Timing's local
	// map).
	CheckInMethod DriverCheckedInV1SchemaJsonCheckInMethod `json:"checkInMethod"`

	// Canonical masterId issued by Identity. Lowercase canonical UUID v4 (version
	// nibble 4, variant nibble [89ab]); the pattern is enforced (format is
	// annotation-only). Read directly from the QR, or resolved from the transponder
	// map. Timing never mints it.
	MasterID string `json:"masterId"`

	// The hardware id when checkInMethod is 'transponder'; null for QR drivers.
	// Always present (no omitempty on a meaningful wire field, AR9).
	TransponderID DriverCheckedInV1SchemaJsonTransponderID `json:"transponderId"`
}

type DriverCheckedInV1SchemaJsonCheckInMethod string

const DriverCheckedInV1SchemaJsonCheckInMethodQr DriverCheckedInV1SchemaJsonCheckInMethod = "qr"
const DriverCheckedInV1SchemaJsonCheckInMethodTransponder DriverCheckedInV1SchemaJsonCheckInMethod = "transponder"

// The hardware id when checkInMethod is 'transponder'; null for QR drivers. Always
// present (no omitempty on a meaningful wire field, AR9).
type DriverCheckedInV1SchemaJsonTransponderID *string

// A valid crossing of the start-finish line. Published to the 'timing.events'
// exchange with routing key 'lap.recorded'.
type LapRecordedV1SchemaJson struct {
	// When the crossing happened. RFC3339 UTC, exactly 3-digit milliseconds, literal
	// 'Z' (AR9). The pattern is enforced (format is annotation-only).
	At string `json:"at"`

	// 1-based; the out-lap (first crossing) is not counted.
	LapNumber int `json:"lapNumber"`

	// Milliseconds since the previous valid crossing.
	LapTimeMs int `json:"lapTimeMs"`

	// Canonical masterId issued by Identity. Lowercase canonical UUID v4 (version
	// nibble 4, variant nibble [89ab]); the pattern is enforced (format is
	// annotation-only).
	MasterID string `json:"masterId"`

	// Session the lap belongs to.
	SessionID string `json:"sessionId"`

	// Hardware id if detected via transponder rather than QR. Optional.
	TransponderID LapRecordedV1SchemaJsonTransponderID `json:"transponderId"`
}

// Hardware id if detected via transponder rather than QR. Optional.
type LapRecordedV1SchemaJsonTransponderID *string

// Timing detected — from the live lap stream — that a driver's counted lap beat
// their all-time personal record held in Timing's local copy (or set their
// first-ever PR). Published to the 'timing.events' exchange with routing key
// 'personal_record.broken'. Driver is the system of record: it confirms the
// canonical PR from its own lap history and re-publishes driver.pr_updated (Story
// 3.4, FR37/FR11); Mailing (Epic 10) may alert on it. previousMs is OMITTED on a
// first-ever PR (there is nothing to beat) and PRESENT (the value just beaten) on
// a subsequent break — Story 3.4 / Q&A Round 37 / Q37.2.
type PersonalRecordBrokenV1SchemaJson struct {
	// The record-setting lap time, in milliseconds (the new best).
	LapTimeMs int `json:"lapTimeMs"`

	// Canonical masterId issued by Identity. Lowercase canonical UUID v4 (version
	// nibble 4, variant nibble [89ab]); the pattern is enforced (format is
	// annotation-only).
	MasterID string `json:"masterId"`

	// The all-time PR that was just beaten, in milliseconds. OPTIONAL: absent on a
	// first-ever PR (nothing to beat). When present, it is strictly greater than
	// lapTimeMs.
	PreviousMs *int `json:"previousMs"`

	// Session the record-setting lap belongs to. Same id space as
	// lap.recorded.sessionId / session.ended.sessionId.
	SessionID string `json:"sessionId"`
}

// The ACTUAL (physical) end of a session plus its summary, emitted by Timing.
// Published to the 'timing.events' exchange with routing key 'session.ended'.
// Consumers: Booking, Billing (close tab), Driver (store summary), Mailing
// (session summary), Leaderboard (mark finished). The per-item shape of
// `summary[]` was pinned by Driver's consume point (Story 3.3, Q&A Round 36 /
// Q36.1): each row requires `masterId` (canonical UUID v4) and carries optional
// `bestLapMs` + `lapCount` — the exact shape Timing already emits. The item object
// stays tolerant (no additionalProperties:false) so a later consumer (e.g.
// Mailing, Epic 10) may pin further fields additively without breaking existing
// producers/consumers.
type SessionEndedV1SchemaJson struct {
	// When the session actually ended. RFC3339 UTC, exactly 3-digit milliseconds,
	// literal 'Z' (AR9). The pattern is enforced (format is annotation-only).
	EndedAt string `json:"endedAt"`

	// The session that ended. Same id space as lap.recorded.sessionId.
	SessionID string `json:"sessionId"`

	// Per-session result rows, one per driver. Item shape pinned in v1 (Story 3.3,
	// Q36.1): masterId required, bestLapMs/lapCount optional; the item stays a
	// tolerant object (additive fields allowed).
	Summary []SessionEndedV1SchemaJsonSummaryElem `json:"summary"`
}

type SessionEndedV1SchemaJsonSummaryElem struct {
	// The driver's best (fastest) valid lap this session, in milliseconds. Optional —
	// absent if the driver logged no counted lap.
	BestLapMs *int `json:"bestLapMs"`

	// Number of counted laps the driver logged this session (out-lap excluded).
	// Optional.
	LapCount *int `json:"lapCount"`

	// Canonical masterId issued by Identity. Lowercase canonical UUID v4 (version
	// nibble 4, variant nibble [89ab]); the pattern is enforced (format is
	// annotation-only).
	MasterID string `json:"masterId"`
}

// The ACTUAL (physical) start of a session, emitted by Timing. Published to the
// 'timing.events' exchange with routing key 'session.started'. Consumers: Booking
// (reconcile plan vs actual), Leaderboard (auto-reset the board), Billing.
type SessionStartedV1SchemaJson struct {
	// The session that started. Same id space as lap.recorded.sessionId.
	SessionID string `json:"sessionId"`

	// When the session actually started. RFC3339 UTC, exactly 3-digit milliseconds,
	// literal 'Z' (AR9). The pattern is enforced (format is annotation-only).
	StartedAt string `json:"startedAt"`
}
