// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package timing

// A driver identified at the entry gate (check-in). Published to the
// 'timing.events' exchange with routing key 'driver.checked_in'. QR codes embed
// the masterId (read directly, no lookup); transponders carry a hardware id
// resolved via Timing's local transponder->masterId map.
type DriverCheckedInV1SchemaJson struct {
	// When the gate scan happened. RFC3339 UTC, exactly 3-digit milliseconds, literal
	// 'Z' (AR9). The pattern is enforced (format is annotation-only).
	At string `json:"at"`

	// How the driver was identified at the gate: 'qr' (masterId read directly from
	// the QR, no lookup) or 'transponder' (hardware id resolved via Timing's local
	// map).
	CheckInMethod DriverCheckedInV1SchemaJsonCheckInMethod `json:"checkInMethod"`

	// Canonical masterId issued by Identity. Lowercase canonical UUID v4 (version
	// nibble 4, variant nibble [89ab]); the pattern is enforced (format is
	// annotation-only). Read directly from the QR, or resolved from the transponder
	// map. Timing never mints it.
	MasterID string `json:"masterId"`

	// The hardware id when checkInMethod is 'transponder'; null for QR drivers.
	// Always present (no omitempty on a meaningful wire field, AR9).
	TransponderID DriverCheckedInV1SchemaJsonTransponderID `json:"transponderId"`
}

type DriverCheckedInV1SchemaJsonCheckInMethod string

const DriverCheckedInV1SchemaJsonCheckInMethodQr DriverCheckedInV1SchemaJsonCheckInMethod = "qr"
const DriverCheckedInV1SchemaJsonCheckInMethodTransponder DriverCheckedInV1SchemaJsonCheckInMethod = "transponder"

// The hardware id when checkInMethod is 'transponder'; null for QR drivers. Always
// present (no omitempty on a meaningful wire field, AR9).
type DriverCheckedInV1SchemaJsonTransponderID *string

// A valid crossing of the start-finish line. Published to the 'timing.events'
// exchange with routing key 'lap.recorded'.
type LapRecordedV1SchemaJson struct {
	// When the crossing happened. RFC3339 UTC, exactly 3-digit milliseconds, literal
	// 'Z' (AR9). The pattern is enforced (format is annotation-only).
	At string `json:"at"`

	// 1-based; the out-lap (first crossing) is not counted.
	LapNumber int `json:"lapNumber"`

	// Milliseconds since the previous valid crossing.
	LapTimeMs int `json:"lapTimeMs"`

	// Canonical masterId issued by Identity. Lowercase canonical UUID v4 (version
	// nibble 4, variant nibble [89ab]); the pattern is enforced (format is
	// annotation-only).
	MasterID string `json:"masterId"`

	// Session the lap belongs to.
	SessionID string `json:"sessionId"`

	// Hardware id if detected via transponder rather than QR. Optional.
	TransponderID LapRecordedV1SchemaJsonTransponderID `json:"transponderId"`
}

// Hardware id if detected via transponder rather than QR. Optional.
type LapRecordedV1SchemaJsonTransponderID *string

// The ACTUAL (physical) end of a session plus its summary, emitted by Timing.
// Published to the 'timing.events' exchange with routing key 'session.ended'.
// Consumers: Booking, Billing (close tab), Driver (store summary), Mailing
// (session summary), Leaderboard (mark finished). NOTE: the per-item shape of
// `summary[]` is NOT pinned by the source corpus and is intentionally left
// tolerant (additionalProperties:true, no required item fields) — no Epic-1
// consumer reads summary contents. Pin the item fields when Driver/Mailing
// actually consume them (Epic 3/10). Confirm-at-build, do not invent.
type SessionEndedV1SchemaJson struct {
	// When the session actually ended. RFC3339 UTC, exactly 3-digit milliseconds,
	// literal 'Z' (AR9). The pattern is enforced (format is annotation-only).
	EndedAt string `json:"endedAt"`

	// The session that ended. Same id space as lap.recorded.sessionId.
	SessionID string `json:"sessionId"`

	// Per-session result rows (e.g. one per driver, with lap times). Item shape
	// intentionally unpinned for v1 — tolerant object.
	Summary []SessionEndedV1SchemaJsonSummaryElem `json:"summary"`
}

type SessionEndedV1SchemaJsonSummaryElem map[string]interface{}

// The ACTUAL (physical) start of a session, emitted by Timing. Published to the
// 'timing.events' exchange with routing key 'session.started'. Consumers: Booking
// (reconcile plan vs actual), Leaderboard (auto-reset the board), Billing.
type SessionStartedV1SchemaJson struct {
	// The session that started. Same id space as lap.recorded.sessionId.
	SessionID string `json:"sessionId"`

	// When the session actually started. RFC3339 UTC, exactly 3-digit milliseconds,
	// literal 'Z' (AR9). The pattern is enforced (format is annotation-only).
	StartedAt string `json:"startedAt"`
}
